<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QNh6YChService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.QNh6YCh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CategorieRecettecontrollerController::index' => ['privates', '.service_locator..tcsuAu.App\\Controller\\CategorieRecettecontrollerController::index()', 'getCategorieRecettecontrollerControllerindexService', true],
            'App\\Controller\\CategorieRecettecontrollerController::nouvelle' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\CategorieRecettecontrollerController::nouvelle()', 'getCategorieRecettecontrollerControllernouvelleService', true],
            'App\\Controller\\FavorisController::index' => ['privates', '.service_locator.Ca0F7z1.App\\Controller\\FavorisController::index()', 'getFavorisControllerindexService', true],
            'App\\Controller\\IngredientController::nouveau' => ['privates', '.service_locator.r9ynYy0.App\\Controller\\IngredientController::nouveau()', 'getIngredientControllernouveauService', true],
            'App\\Controller\\IngredientController::supprimer' => ['privates', '.service_locator.kPUbVqv.App\\Controller\\IngredientController::supprimer()', 'getIngredientControllersupprimerService', true],
            'App\\Controller\\RecettesController::index' => ['privates', '.service_locator.LCXzXFA.App\\Controller\\RecettesController::index()', 'getRecettesControllerindexService', true],
            'App\\Controller\\RecettesController::nouvelle' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\RecettesController::nouvelle()', 'getRecettesControllernouvelleService', true],
            'App\\Controller\\RecettesController::details' => ['privates', '.service_locator.A30mISa.App\\Controller\\RecettesController::details()', 'getRecettesControllerdetailsService', true],
            'App\\Controller\\RecettesController::modifier' => ['privates', '.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()', 'getRecettesControllermodifierService', true],
            'App\\Controller\\RecettesController::supprimer' => ['privates', '.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()', 'getRecettesControllersupprimerService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.TgjTaHZ.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\TagRecettecontrollerController::index' => ['privates', '.service_locator.7zeK6Sq.App\\Controller\\TagRecettecontrollerController::index()', 'getTagRecettecontrollerControllerindexService', true],
            'App\\Controller\\TagRecettecontrollerController::nouvelle' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\TagRecettecontrollerController::nouvelle()', 'getTagRecettecontrollerControllernouvelleService', true],
            'App\\Controller\\TagRecettecontrollerController::supprimer' => ['privates', '.service_locator.UfF7Xwr.App\\Controller\\TagRecettecontrollerController::supprimer()', 'getTagRecettecontrollerControllersupprimerService', true],
            'App\\Controller\\adminRequestsController::index' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\adminRequestsController::index()', 'getAdminRequestsControllerindexService', true],
            'App\\Controller\\adminRequestsController::approve' => ['privates', '.service_locator.kx3VP28.App\\Controller\\adminRequestsController::approve()', 'getAdminRequestsControllerapproveService', true],
            'App\\Controller\\adminRequestsController::reject' => ['privates', '.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()', 'getAdminRequestsControllerrejectService', true],
            'App\\Controller\\loginController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\loginController::login()', 'getLoginControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CategorieRecettecontrollerController:index' => ['privates', '.service_locator..tcsuAu.App\\Controller\\CategorieRecettecontrollerController::index()', 'getCategorieRecettecontrollerControllerindexService', true],
            'App\\Controller\\CategorieRecettecontrollerController:nouvelle' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\CategorieRecettecontrollerController::nouvelle()', 'getCategorieRecettecontrollerControllernouvelleService', true],
            'App\\Controller\\FavorisController:index' => ['privates', '.service_locator.Ca0F7z1.App\\Controller\\FavorisController::index()', 'getFavorisControllerindexService', true],
            'App\\Controller\\IngredientController:nouveau' => ['privates', '.service_locator.r9ynYy0.App\\Controller\\IngredientController::nouveau()', 'getIngredientControllernouveauService', true],
            'App\\Controller\\IngredientController:supprimer' => ['privates', '.service_locator.kPUbVqv.App\\Controller\\IngredientController::supprimer()', 'getIngredientControllersupprimerService', true],
            'App\\Controller\\RecettesController:index' => ['privates', '.service_locator.LCXzXFA.App\\Controller\\RecettesController::index()', 'getRecettesControllerindexService', true],
            'App\\Controller\\RecettesController:nouvelle' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\RecettesController::nouvelle()', 'getRecettesControllernouvelleService', true],
            'App\\Controller\\RecettesController:details' => ['privates', '.service_locator.A30mISa.App\\Controller\\RecettesController::details()', 'getRecettesControllerdetailsService', true],
            'App\\Controller\\RecettesController:modifier' => ['privates', '.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()', 'getRecettesControllermodifierService', true],
            'App\\Controller\\RecettesController:supprimer' => ['privates', '.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()', 'getRecettesControllersupprimerService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.TgjTaHZ.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\TagRecettecontrollerController:index' => ['privates', '.service_locator.7zeK6Sq.App\\Controller\\TagRecettecontrollerController::index()', 'getTagRecettecontrollerControllerindexService', true],
            'App\\Controller\\TagRecettecontrollerController:nouvelle' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\TagRecettecontrollerController::nouvelle()', 'getTagRecettecontrollerControllernouvelleService', true],
            'App\\Controller\\TagRecettecontrollerController:supprimer' => ['privates', '.service_locator.UfF7Xwr.App\\Controller\\TagRecettecontrollerController::supprimer()', 'getTagRecettecontrollerControllersupprimerService', true],
            'App\\Controller\\adminRequestsController:index' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\adminRequestsController::index()', 'getAdminRequestsControllerindexService', true],
            'App\\Controller\\adminRequestsController:approve' => ['privates', '.service_locator.kx3VP28.App\\Controller\\adminRequestsController::approve()', 'getAdminRequestsControllerapproveService', true],
            'App\\Controller\\adminRequestsController:reject' => ['privates', '.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()', 'getAdminRequestsControllerrejectService', true],
            'App\\Controller\\loginController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\loginController::login()', 'getLoginControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategorieRecettecontrollerController::index' => '?',
            'App\\Controller\\CategorieRecettecontrollerController::nouvelle' => '?',
            'App\\Controller\\FavorisController::index' => '?',
            'App\\Controller\\IngredientController::nouveau' => '?',
            'App\\Controller\\IngredientController::supprimer' => '?',
            'App\\Controller\\RecettesController::index' => '?',
            'App\\Controller\\RecettesController::nouvelle' => '?',
            'App\\Controller\\RecettesController::details' => '?',
            'App\\Controller\\RecettesController::modifier' => '?',
            'App\\Controller\\RecettesController::supprimer' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\TagRecettecontrollerController::index' => '?',
            'App\\Controller\\TagRecettecontrollerController::nouvelle' => '?',
            'App\\Controller\\TagRecettecontrollerController::supprimer' => '?',
            'App\\Controller\\adminRequestsController::index' => '?',
            'App\\Controller\\adminRequestsController::approve' => '?',
            'App\\Controller\\adminRequestsController::reject' => '?',
            'App\\Controller\\loginController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategorieRecettecontrollerController:index' => '?',
            'App\\Controller\\CategorieRecettecontrollerController:nouvelle' => '?',
            'App\\Controller\\FavorisController:index' => '?',
            'App\\Controller\\IngredientController:nouveau' => '?',
            'App\\Controller\\IngredientController:supprimer' => '?',
            'App\\Controller\\RecettesController:index' => '?',
            'App\\Controller\\RecettesController:nouvelle' => '?',
            'App\\Controller\\RecettesController:details' => '?',
            'App\\Controller\\RecettesController:modifier' => '?',
            'App\\Controller\\RecettesController:supprimer' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\TagRecettecontrollerController:index' => '?',
            'App\\Controller\\TagRecettecontrollerController:nouvelle' => '?',
            'App\\Controller\\TagRecettecontrollerController:supprimer' => '?',
            'App\\Controller\\adminRequestsController:index' => '?',
            'App\\Controller\\adminRequestsController:approve' => '?',
            'App\\Controller\\adminRequestsController:reject' => '?',
            'App\\Controller\\loginController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.QNh6YCh'])) {
            return $container->privates['.service_locator.QNh6YCh'];
        }

        return $container->privates['.service_locator.QNh6YCh'] = $instance;
    }
}
