<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kx3VP28Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.kx3VP28' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'entityManager' => '?',
            'mailer' => 'App\\Service\\MailerService',
        ]);

        if (isset($container->privates['.service_locator.kx3VP28'])) {
            return $container->privates['.service_locator.kx3VP28'];
        }

        return $container->privates['.service_locator.kx3VP28'] = $instance;
    }
}
