<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Serializer_ContextBuilder_Filter_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.serializer.context_builder.filter.inner' shared service.
     *
     * @return \ApiPlatform\Serializer\SerializerContextBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/SerializerContextBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/serializer/SerializerContextBuilder.php';

        $a = ($container->privates['api_platform.doctrine.orm.metadata.resource.metadata_collection_factory'] ?? self::getApiPlatform_Doctrine_Orm_Metadata_Resource_MetadataCollectionFactoryService($container));

        if (isset($container->privates['api_platform.serializer.context_builder.filter.inner'])) {
            return $container->privates['api_platform.serializer.context_builder.filter.inner'];
        }

        $instance = new \ApiPlatform\Serializer\SerializerContextBuilder($a, true);

        if (isset($container->privates['api_platform.serializer.context_builder.filter.inner'])) {
            return $container->privates['api_platform.serializer.context_builder.filter.inner'];
        }

        return $container->privates['api_platform.serializer.context_builder.filter.inner'] = $instance;
    }
}
