<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminRequestsControllerrejectService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.kx3VP28.App\Controller\adminRequestsController::reject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.kx3VP28'] ?? $container->load('get_ServiceLocator_Kx3VP28Service'));

        if (isset($container->privates['.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()'])) {
            return $container->privates['.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()'];
        }

        $instance = $a->withContext('App\\Controller\\adminRequestsController::reject()', $container);

        if (isset($container->privates['.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()'])) {
            return $container->privates['.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()'];
        }

        return $container->privates['.service_locator.kx3VP28.App\\Controller\\adminRequestsController::reject()'] = $instance;
    }
}
