<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Hydra_JsonSchema_SchemaFactory_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.hydra.json_schema.schema_factory.inner' shared service.
     *
     * @return \ApiPlatform\JsonSchema\SchemaFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaFactoryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/ResourceMetadataTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaUriPrefixTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/SchemaFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/DefinitionNameFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/json-schema/DefinitionNameFactory.php';

        $a = ($container->privates['api_platform.doctrine.orm.metadata.resource.metadata_collection_factory'] ?? self::getApiPlatform_Doctrine_Orm_Metadata_Resource_MetadataCollectionFactoryService($container));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory.inner'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory.inner'];
        }
        $b = ($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory.inner'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory.inner'];
        }
        $c = ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory.inner'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory.inner'];
        }

        $instance = new \ApiPlatform\JsonSchema\SchemaFactory($a, $b, $c, ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), [], ($container->privates['api_platform.json_schema.definition_name_factory'] ??= new \ApiPlatform\JsonSchema\DefinitionNameFactory()));

        if (isset($container->privates['api_platform.hydra.json_schema.schema_factory.inner'])) {
            return $container->privates['api_platform.hydra.json_schema.schema_factory.inner'];
        }

        return $container->privates['api_platform.hydra.json_schema.schema_factory.inner'] = $instance;
    }
}
