<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/FixturesProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Fixture.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AppFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/CategorieRecetteFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/IngredientFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/RecetteFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/TagRecetteFixtures.php';

        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader();

        $instance->addFixtures([['fixture' => ($container->privates['App\\DataFixtures\\AppFixtures'] ??= new \App\DataFixtures\AppFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\CategorieRecetteFixtures'] ??= new \App\DataFixtures\CategorieRecetteFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\IngredientFixtures'] ??= new \App\DataFixtures\IngredientFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\RecetteFixtures'] ??= new \App\DataFixtures\RecetteFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\TagRecetteFixtures'] ??= new \App\DataFixtures\TagRecetteFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\UserFixtures'] ?? $container->load('getUserFixturesService')), 'groups' => []]]);

        return $instance;
    }
}
