<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_Loader_Attribute_ServicesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'routing.loader.attribute.services' shared service.
     *
     * @return \Symfony\Component\Routing\Loader\AttributeServicesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Loader/AttributeServicesLoader.php';

        return $container->privates['routing.loader.attribute.services'] = new \Symfony\Component\Routing\Loader\AttributeServicesLoader(['App\\Controller\\AccueilController', 'App\\Controller\\CategorieRecettecontrollerController', 'App\\Controller\\EditRecetteController', 'App\\Controller\\FavorisController', 'App\\Controller\\IngredientController', 'App\\Controller\\RecettesController', 'App\\Controller\\RegistrationController', 'App\\Controller\\TagRecettecontrollerController', 'App\\Controller\\adminRequestsController', 'App\\Controller\\loginController', 'App\\Controller\\newRecetteController']);
    }
}
