<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\RecettesController' shared autowired service.
     *
     * @return \App\Controller\RecettesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RecettesController.php';

        $container->services['App\\Controller\\RecettesController'] = $instance = new \App\Controller\RecettesController(($container->privates['App\\Service\\RecetteAnalyser'] ?? $container->load('getRecetteAnalyserService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\RecettesController', $container));

        return $instance;
    }
}
