<?php

namespace ContainerXrjcv45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagRecettecontrollerControllersupprimerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.UfF7Xwr.App\Controller\TagRecettecontrollerController::supprimer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tagrecette' => ['privates', '.errored..service_locator.UfF7Xwr.App\\Entity\\TagRecette', NULL, 'Cannot autowire service ".service_locator.UfF7Xwr": it needs an instance of "App\\Entity\\TagRecette" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'tagrecette' => 'App\\Entity\\TagRecette',
            'em' => '?',
        ]))->withContext('App\\Controller\\TagRecettecontrollerController::supprimer()', $container);

        if (isset($container->privates['.service_locator.UfF7Xwr.App\\Controller\\TagRecettecontrollerController::supprimer()'])) {
            return $container->privates['.service_locator.UfF7Xwr.App\\Controller\\TagRecettecontrollerController::supprimer()'];
        }

        return $container->privates['.service_locator.UfF7Xwr.App\\Controller\\TagRecettecontrollerController::supprimer()'] = $instance;
    }
}
