<?php

namespace ContainerOXjNqxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TuX2pMFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tuX2pMF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tuX2pMF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', '.errored.lV0jSE3', NULL, 'Cannot determine controller argument for "App\\Controller\\RecetteController::index()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Controller\\RecetteRepository". Did you forget to add a use statement?'],
        ], [
            'repo' => '?',
        ]);
    }
}
