<?php

namespace ContainerOXjNqxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Au4IJrsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Au4IJrs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\RecetteController::index' => ['privates', '.service_locator.tuX2pMF', 'get_ServiceLocator_TuX2pMFService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\loginController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\loginController::login()', 'getLoginControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\RecetteController:index' => ['privates', '.service_locator.tuX2pMF', 'get_ServiceLocator_TuX2pMFService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\loginController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\loginController::login()', 'getLoginControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RecetteController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\loginController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RecetteController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\loginController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.Au4IJrs'])) {
            return $container->privates['.service_locator.Au4IJrs'];
        }

        return $container->privates['.service_locator.Au4IJrs'] = $instance;
    }
}
