<?php

namespace ContainerOXjNqxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_LV0jSE3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.lV0jSE3' shared service.
     *
     * @return \App\Controller\RecetteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecetteController::index()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Controller\\RecetteRepository". Did you forget to add a use statement?');
    }
}
