<?php

namespace ContainerH1wARJ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieRecettecontrollerControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..tcsuAu.App\Controller\CategorieRecettecontrollerController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..tcsuAu.App\\Controller\\CategorieRecettecontrollerController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRecetteRepository', 'getCategorieRecetteRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRecetteRepository',
        ]))->withContext('App\\Controller\\CategorieRecettecontrollerController::index()', $container);
    }
}
