<?php

namespace ContainerH1wARJ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesControllerdetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A30mISa.App\Controller\RecettesController::details()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A30mISa.App\\Controller\\RecettesController::details()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recette' => ['privates', '.errored..service_locator.A30mISa.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator.A30mISa": it needs an instance of "App\\Entity\\Recette" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'recette' => 'App\\Entity\\Recette',
        ]))->withContext('App\\Controller\\RecettesController::details()', $container);
    }
}
