<?php

namespace ContainerH1wARJ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagRecettecontrollerControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7zeK6Sq.App\Controller\TagRecettecontrollerController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7zeK6Sq.App\\Controller\\TagRecettecontrollerController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trecR' => ['privates', 'App\\Repository\\TagRecetteRepository', 'getTagRecetteRepositoryService', true],
        ], [
            'trecR' => 'App\\Repository\\TagRecetteRepository',
        ]))->withContext('App\\Controller\\TagRecettecontrollerController::index()', $container);
    }
}
