<?php

namespace ContainerDxVanRS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KPUbVqvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kPUbVqv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recette' => ['privates', '.errored..service_locator.kPUbVqv.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator.kPUbVqv": it needs an instance of "App\\Entity\\Recette" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'recette' => 'App\\Entity\\Recette',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.kPUbVqv'])) {
            return $container->privates['.service_locator.kPUbVqv'];
        }

        return $container->privates['.service_locator.kPUbVqv'] = $instance;
    }
}
