<?php

namespace ContainerDxVanRS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagrecetteTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TagrecetteType' shared autowired service.
     *
     * @return \App\Form\TagrecetteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TagrecetteType.php';

        return $container->privates['App\\Form\\TagrecetteType'] = new \App\Form\TagrecetteType();
    }
}
