<?php

namespace Container9lFx9X3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeHubStatsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RecipeHubStatsCommand' shared autowired service.
     *
     * @return \App\Command\RecipeHubStatsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RecipeHubStatsCommand.php';

        $container->privates['App\\Command\\RecipeHubStatsCommand'] = $instance = new \App\Command\RecipeHubStatsCommand(($container->privates['App\\Repository\\RecetteRepository'] ?? $container->load('getRecetteRepositoryService')), ($container->privates['App\\Repository\\CategorieRecetteRepository'] ?? $container->load('getCategorieRecetteRepositoryService')), ($container->privates['App\\Repository\\IngredientRepository'] ?? $container->load('getIngredientRepositoryService')));

        $instance->setName('app:recipehub:stats');
        $instance->setDescription('Affiche les statistiques de la plateforme de recettes');

        return $instance;
    }
}
