<?php

namespace Container9lFx9X3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RecettesController' shared autowired service.
     *
     * @return \App\Controller\RecettesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RecettesController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RecetteAnalyser.php';

        $container->services['App\\Controller\\RecettesController'] = $instance = new \App\Controller\RecettesController(new \App\Service\RecetteAnalyser(($container->privates['App\\Repository\\RecetteRepository'] ?? $container->load('getRecetteRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\RecettesController', $container));

        return $instance;
    }
}
