<?php

namespace Container9lFx9X3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesControllersupprimerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kPUbVqv.App\Controller\RecettesController::supprimer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.kPUbVqv'] ?? $container->load('get_ServiceLocator_KPUbVqvService'));

        if (isset($container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()'])) {
            return $container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()'];
        }

        $instance = $a->withContext('App\\Controller\\RecettesController::supprimer()', $container);

        if (isset($container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()'])) {
            return $container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()'];
        }

        return $container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::supprimer()'] = $instance;
    }
}
