<?php

namespace Container1rZxCfj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesControllermodifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kPUbVqv.App\Controller\RecettesController::modifier()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.kPUbVqv'] ?? $container->load('get_ServiceLocator_KPUbVqvService'));

        if (isset($container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()'])) {
            return $container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()'];
        }

        $instance = $a->withContext('App\\Controller\\RecettesController::modifier()', $container);

        if (isset($container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()'])) {
            return $container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()'];
        }

        return $container->privates['.service_locator.kPUbVqv.App\\Controller\\RecettesController::modifier()'] = $instance;
    }
}
