# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json


parameters:
# Hna t7ot el path mta3 el dossier win bech t-sauvi el tsawer
    images_directory: '%kernel.project_dir%/public/img'

services:

    
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # ✅ FileUploader service (IMPORTANT for your project)
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'
