<?php

namespace ContainerJzoypZj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavorisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ca0F7z1.App\Controller\FavorisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ca0F7z1.App\\Controller\\FavorisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\RecetteRepository', 'getRecetteRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\RecetteRepository',
        ]))->withContext('App\\Controller\\FavorisController::index()', $container);
    }
}
