<?php

namespace ContainerJzoypZj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagRecetteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UfF7Xwr.App\Entity\TagRecette' shared service.
     *
     * @return \App\Entity\TagRecette
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UfF7Xwr": it needs an instance of "App\\Entity\\TagRecette" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
