<?php

namespace Container8N8x0rt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminRequestsControllerapproveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4eE5_7S.App\Controller\adminRequestsController::approve()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.4eE5_7S'] ?? $container->load('get_ServiceLocator_4eE57SService'));

        if (isset($container->privates['.service_locator.4eE5_7S.App\\Controller\\adminRequestsController::approve()'])) {
            return $container->privates['.service_locator.4eE5_7S.App\\Controller\\adminRequestsController::approve()'];
        }

        $instance = $a->withContext('App\\Controller\\adminRequestsController::approve()', $container);

        if (isset($container->privates['.service_locator.4eE5_7S.App\\Controller\\adminRequestsController::approve()'])) {
            return $container->privates['.service_locator.4eE5_7S.App\\Controller\\adminRequestsController::approve()'];
        }

        return $container->privates['.service_locator.4eE5_7S.App\\Controller\\adminRequestsController::approve()'] = $instance;
    }
}
