<?php

namespace Container8N8x0rt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeHubStatsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\RecipeHubStatsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\RecipeHubStatsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:recipehub:stats', [], 'Affiche les statistiques de la plateforme de recettes', false, #[\Closure(name: 'App\\Command\\RecipeHubStatsCommand')] fn (): \App\Command\RecipeHubStatsCommand => ($container->privates['App\\Command\\RecipeHubStatsCommand'] ?? $container->load('getRecipeHubStatsCommandService')));
    }
}
