<?php

namespace Container8N8x0rt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteAnalyserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RecetteAnalyser' shared autowired service.
     *
     * @return \App\Service\RecetteAnalyser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RecetteAnalyser.php';

        return $container->privates['App\\Service\\RecetteAnalyser'] = new \App\Service\RecetteAnalyser(($container->privates['App\\Repository\\RecetteRepository'] ?? $container->load('getRecetteRepositoryService')));
    }
}
