<?php

namespace Container8N8x0rt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LCXzXFA.App\Controller\RecettesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\RecetteRepository', 'getRecetteRepositoryService', true],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRecetteRepository', 'getCategorieRecetteRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'analyser' => ['privates', 'App\\Service\\RecetteAnalyser', 'getRecetteAnalyserService', true],
        ], [
            'repo' => 'App\\Repository\\RecetteRepository',
            'catRepo' => 'App\\Repository\\CategorieRecetteRepository',
            'paginator' => '?',
            'analyser' => 'App\\Service\\RecetteAnalyser',
        ]))->withContext('App\\Controller\\RecettesController::index()', $container);

        if (isset($container->privates['.service_locator.LCXzXFA.App\\Controller\\RecettesController::index()'])) {
            return $container->privates['.service_locator.LCXzXFA.App\\Controller\\RecettesController::index()'];
        }

        return $container->privates['.service_locator.LCXzXFA.App\\Controller\\RecettesController::index()'] = $instance;
    }
}
