<?php

namespace ContainerIILNSMb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Nd2JziService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Nd2Jzi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\FavorisController::index' => ['privates', '.service_locator.Ca0F7z1.App\\Controller\\FavorisController::index()', 'getFavorisControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\loginController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\loginController::login()', 'getLoginControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\FavorisController:index' => ['privates', '.service_locator.Ca0F7z1.App\\Controller\\FavorisController::index()', 'getFavorisControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\loginController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\loginController::login()', 'getLoginControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\FavorisController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\loginController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\FavorisController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\loginController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.0Nd2Jzi'])) {
            return $container->privates['.service_locator.0Nd2Jzi'];
        }

        return $container->privates['.service_locator.0Nd2Jzi'] = $instance;
    }
}
