<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPglad4e\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPglad4e/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPglad4e.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPglad4e\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPglad4e\App_KernelTestDebugContainer([
    'container.build_hash' => 'Pglad4e',
    'container.build_id' => 'fd70a1ac',
    'container.build_time' => 1778523118,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPglad4e');
