<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrjcv45\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrjcv45/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXrjcv45.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXrjcv45\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXrjcv45\App_KernelTestDebugContainer([
    'container.build_hash' => 'Xrjcv45',
    'container.build_id' => 'c3330c72',
    'container.build_time' => 1778343404,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrjcv45');
