<?php

namespace Container00v1nLu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagRecettecontrollerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TagRecettecontrollerController' shared autowired service.
     *
     * @return \App\Controller\TagRecettecontrollerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TagRecettecontrollerController.php';

        $container->services['App\\Controller\\TagRecettecontrollerController'] = $instance = new \App\Controller\TagRecettecontrollerController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\TagRecettecontrollerController', $container));

        return $instance;
    }
}
