<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container176kSrm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container176kSrm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container176kSrm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container176kSrm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container176kSrm\App_KernelDevDebugContainer([
    'container.build_hash' => '176kSrm',
    'container.build_id' => 'bc932512',
    'container.build_time' => 1777985522,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container176kSrm');
