<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8N8x0rt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8N8x0rt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8N8x0rt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8N8x0rt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8N8x0rt\App_KernelDevDebugContainer([
    'container.build_hash' => '8N8x0rt',
    'container.build_id' => 'b9ed18fc',
    'container.build_time' => 1778158916,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8N8x0rt');
